language: cpp
sudo: required
dist: trusty
compiler:
  #- clang error
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libeigen3-dev libboost-all-dev
install:
  - ( mkdir build && cd build && cmake ../src -DCMAKE_BUILD_TYPE=Release && make -j 4 )
script:
  - build/sharpPI -h 
  - (cd tests && ./test_biondi.sh)
