language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libeigen3-dev libboost-all-dev
install:
  - ( mkdir build && cd build && cmake ../src -DCMAKE_BUILD_TYPE=Release && make -j 4 )
script:
  - build/sharpPI -h 
  - time build/sharpPI  -i @I -o global_consumption tests/all_houses_12_A.cnf
