language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libeigen3-dev libboost-all-dev
install:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
script:
  # currently no test except compilation
